config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  post :day_forms, to: 'day_forms#create'
  put :day_forms, to: 'day_forms#update'

  resources :users, only: [:new, :show, :create] do
    resources :days, only: [:new, :show, :create, :edit, :destroy]
    resources :day_forms, only: [:edit]
  end

  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :day_recipes, dependent: :destroy
  has_many :recipes, through: :day_recipes

  belongs_to :user

  validates :date, presence: true, uniqueness: true
  validates :user, presence: true
  validates :recipes, presence: true
  validate :recipe_length

  def recipe_length
    self.recipes == 4
  end

  def total_calories
    recipes.map{|r| r.calories_per_serving}.sum
  end
end

app/models/day_form.rb
class DayForm
  include ActiveModel::Model

  validates :date, presence: true
  validates :user_id, presence: true

  attr_accessor :date, :user_id, :breakfast_id, :lunch_id, :dinner_id, :snack_id

  def self.from_day(day)
    df = DayForm.new
    df.user_id = day.user.id
    df.date = day.date
    recipes = day.recipes
    df.breakfast_id = recipes[0].id
    df.lunch_id = recipes[1].id
    df.dinner_id = recipes[2].id
    df.snack_id = recipes[3].id
    df
  end

  def create(day)
    return false unless valid?
    user = User.find(user_id)
    breakfast = Recipe.find(breakfast_id)
    lunch = Recipe.find(lunch_id)
    dinner = Recipe.find(dinner_id)
    snack = Recipe.find(snack_id)
    day.user = user
    day.date = date
    day.recipes = [breakfast, lunch, dinner, snack]
    day.save
  end

  def update(day, day_form_params)
    return false unless valid?
    day.recipes.clear
    breakfast = Recipe.find(breakfast_id)
    lunch = Recipe.find(lunch_id)
    dinner = Recipe.find(dinner_id)
    snack = Recipe.find(snack_id)
    day.recipes = [breakfast, lunch, dinner, snack]
    day.save
  end
end

app/models/day_recipe.rb
class DayRecipe < ApplicationRecord
  belongs_to :day
  belongs_to :recipe
end

app/models/day_recipes.rb
class DayRecipes < ApplicationRecord
  belongs_to :day
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :day_recipes
  has_many :days, through: :day_recipes

  validates :name, presence: true, uniqueness: true
  validates :calories, presence: true, numericality: true
  validates :servings, presence: true, numericality: true

  def calories_per_serving
    calories/servings
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :days
  has_many :day_recipes, through: :days
  has_many :recipes, through: :day_recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :authorize_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize_user
    id = params[:user_id] || params[:id]
    render file: '/public/404' unless current_user == User.find(id)
  end
end

app/controllers/day_forms_controller.rb
class DayFormsController < ApplicationController

  def create
    @day_form = DayForm.new(day_form_params)
      day = Day.new
      if @day_form.create(day)
        redirect_to user_day_path(day.user, day.id), notice: 'Meal Plan Created!'
      else
        redirect_to new_user_day_path(day_form_params[:user_id]), notice: "Errors creating your meal plan."
      end
  end

  def edit
    day = Day.find(params[:id])
    @day_form = DayForm.from_day(day)
  end

  def update
    @day_form = DayForm.new(day_form_params)
      @day = Day.find_by(date: day_form_params[:date])
    if @day_form.update(@day, day_form_params)
      redirect_to user_day_path(@day.user, @day.id), notice: 'Meal Plan Updated!'
    else
      redirect_to edit_user_day_path(day_form_params[:user_id], @day), notice: @day.errors.messages
    end
  end

  private

  def day_form_params
    params.require(:day_form).permit(:date, :user_id, :breakfast_id, :lunch_id, :dinner_id, :snack_id)
  end
end

app/controllers/days_controller.rb
require 'date'

class DaysController < ApplicationController
  before_action :authorize_user

  def new
    @day = Day.new
    @day.user = User.find(params[:user_id])
    @day.date = Date.today
    while Day.find_by(date: @day.date)
      @day.date += 1
    end
  end

  def show
    @day = Day.find(params[:id])
    @recipes = @day.recipes
  end

  def edit
    @day = Day.find(params[:id])
  end

  def destroy
    @day = Day.find(params[:id])
    @user = @day.user

    if @day.destroy
      flash[:notice] = "Meal Plan Deleted!"
      redirect_to user_path(@user)
    else
      flash[:error] = "Error Deleting Meal Plan!"
      redirect_to user_path(@user)
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    flash[:notice] = "Recipe Created!"

    redirect_to recipe_path(@recipe)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.update(recipe_params)
    if @recipe
      flash[:notice] = "Recipe Updated!"
    else
      flash[:error] = "Errors Updating Your Recipe!"
    end

    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:notice] = "Recipe Deleted!"
    else
      flash[:error] = "Error Deleting Your Recipe!"
    end

    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :calories, :servings)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Successful login"

      redirect_to user_path(@user)
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Goodbye'
    
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_user, only: [:show]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @days = @user.days.all
  end

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    flash[:notice] = "Successful login"

    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/day_forms/_form.html.erb
  <%= f.hidden_field(:date, name: 'day_form[date]', value: @day_form.date) %>
  <%= f.hidden_field(:user_id, name: 'day_form[user_id]', value: @day_form.user_id) %>

  <h3><%= f.label :breakfast %>:</h3>
  <%= select("day_form", "breakfast_id", Recipe.all.collect {|r| [r.name, r.id]}) %>

  <br>
  <br>

  <h3><%= f.label :lunch %>:</h3>
  <%= select("day_form", "lunch_id", Recipe.all.collect {|r| [r.name, r.id]}) %>

  <br>
  <br>

  <h3><%= f.label :dinner %>:</h3>
  <%= select("day_form", "dinner_id", Recipe.all.collect {|r| [r.name, r.id]}) %>

  <br>
  <br>

  <h3><%= f.label :snack %>:</h3>
  <%= select("day_form", "snack_id", Recipe.all.collect {|r| [r.name, r.id]}) %>

  <br>
  <br>
  <br>

app/views/day_forms/edit.html.erb
  <h1>Edit Meal Plan for: </h1>
    <h3><%="#{@day_form.date.strftime('%A, %B %d, %Y')}" %></h3>
  <hr>
<div class="container">
  <div class="col-md-4 col-md-offset-4">
    <%= bootstrap_form_for(@day_form,
                           html: {id: 'day_form'},
                           url: day_forms_path, method: :put) do |f| %>
      <%= render partial: "form", locals: { f: f } %>
      <%= f.submit "Update Meal Plan" %>
    <% end %>
  </div>
</div>

app/views/day_recipes/new.html.erb
<h1>Create a New Meal Plan:</h1>

<% render partial: "form" %>

app/views/days/_form.html.erb
  <%= f.hidden_field(:date, name: 'day_form[date]', value: @day.date) %>
  <%= f.hidden_field(:user_id, name: 'day_form[user_id]', value: @day.user.id) %>

  <h3><%= f.label :breakfast %>:</h3>
  <%= select("day_form", "breakfast_id", Recipe.all.collect {|r| [r.name, r.id]}) %>

  <br>
  <br>

  <h3><%= f.label :lunch %>:</h3>
  <%= select("day_form", "lunch_id", Recipe.all.collect {|r| [r.name, r.id]}) %>

  <br>
  <br>

  <h3><%= f.label :dinner %>:</h3>
  <%= select("day_form", "dinner_id", Recipe.all.collect {|r| [r.name, r.id]}) %>

  <br>
  <br>

  <h3><%= f.label :snack %>:</h3>
  <%= select("day_form", "snack_id", Recipe.all.collect {|r| [r.name, r.id]}) %>

  <br>
  <br>
  <br>

app/views/days/edit.html.erb
  <h1>Edit Meal Plan for: </h1>
    <h3><%= "#{@day.date.strftime('%A, %B %d, %Y')}" %></h3>
  <hr>

<div class="container">
  <div class="col-md-4 col-md-offset-4">
    <%= bootstrap_form_for(:day_form,
                 html: {id: 'day_form'},
                 url: day_forms_path, method: :put) do |f| %>

    <%= render partial: "form", locals: { f: f } %>

    <%= f.submit "Update Meal Plan" %>
    <% end %>
  </div>
</div>

app/views/days/new.html.erb
<h1>Create a New Meal Plan for: </h1>
  <h3><%= "#{@day.date.strftime('%A, %B %d, %Y')}" %></h3>
<hr>

<div class="col-md-4 col-md-offset-4 text-center">
  <%= bootstrap_form_for(:day_form,
               html: {id: 'day_form'},
               url: day_forms_path) do |f| %>

  <%= render partial: "form", locals: { f: f } %>

  <%= f.submit "Create Meal Plan" %>
  <% end %>
</div>

app/views/days/show.html.erb
  <h1> Meal Plan for: </h1>
    <h3><%= "#{@day.date.strftime('%A, %B %d, %Y')}" %></h3>
    <%= button_to "Back to Meal Plans", user_path(@day.user), method: :get, class: "btn btn-default" %>
  <hr>

<div class="container text-center">
  <% @recipes.each do |recipe| %>
    <h3><%= recipe.name %></h3><br>
    <p><strong>Calories per Serving:</strong> <%= recipe.calories_per_serving %></p>
  <% end %>
  <br>
  <hr>
  <strong>Total Calories:</strong> <%= @day.total_calories %>
  <hr>
  <%= button_to "Edit Meal Plan", edit_user_day_path(@day.user, @day), method: :get, class: "btn btn-default" %>
  <%= button_to "Delete Meal Plan", user_day_path(@day.user, @day), method: :delete, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mekase</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Mekase</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Welcome, <%= "#{current_user.username.capitalize}" %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="/users/<%="#{current_user.id}"%>">Your Meal Plans</a>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="/recipes">View All Recipes</a>
              </li>
              <li>
                <a href="/recipes/new">New Recipe</a>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to 'Logout', logout_path, method: :delete %>
          </li>
          <% else %>
            <li>
              <a href="/users/new">Create Account</a>
            </li>
            <li>
              <a href="/login">Login</a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <% if name == 'error' %>
        <%= content_tag :div, msg, :class => "alert alert-danger", :role => "alert" %>
      <% else %>
        <%= content_tag :div, msg, :class => "alert alert-success", :role=> "alert" %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
  
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  </body>
</html>

app/views/recipes/_form.html.erb
<%= bootstrap_form_for @recipe do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :calories %>
  <%= f.text_field :servings %>
  <%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
  <h1>Update <%= @recipe.name %>:</h1>
  <hr>

  <div class="col-md-4 col-md-offset-4">
  <%= render partial: "form" %>
  </div>

app/views/recipes/index.html.erb
  <h1>All Recipes</h1>
    <%= button_to "Create New Recipe", new_recipe_path, method: :get, class: "btn btn-default" %>
  <hr>

<div class="row">
    <% @recipes.each do |recipe| %>
      <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
            <p><strong>Total Calories:</strong> <%= recipe.calories %><br>
               <strong>Servings:</strong> <%= recipe.servings %><br>
               <strong>Calories per Serving:</strong> <%= recipe.calories_per_serving %></p>
              <hr>
              <%= button_to "Edit Recipe", edit_recipe_path(recipe), method: :get, class: "btn btn-default" %>
              <%= button_to "Delete Recipe", recipe_path(recipe), method: :delete, class: "btn btn-default"%>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
  <h1>Create New Recipe:</h1>
  <hr>

<div class="container">
  <div class="col-md-4 col-md-offset-4">
  <%= render partial: "form" %>
  </div>
</div>

app/views/recipes/show.html.erb
  <h1><%= @recipe.name %></h1>
  <hr>
<div class="container">
  <div class="col-md-4 col-md-offset-4">
    <div class="thumbnail">
      <div class="caption">
        <p><strong>Total Calories:</strong> <%= @recipe.calories %><br>
           <strong>Servings:</strong> <%= @recipe.servings %><br>
           <strong>Calories per Serving:</strong> <%= @recipe.calories_per_serving %></p>
          <hr>
          <%= button_to "Edit Recipe", edit_recipe_path(@recipe), method: :get, class: "btn btn-default" %>
          <%= button_to "Delete Recipe", recipe_path(@recipe), method: :delete, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= bootstrap_form_for @user do |f| %>
    <%= f.text_field :username %>
    <%= f.password_field :password %>
  <%= f.submit "Create Account"%>
<% end %>

app/views/users/new.html.erb
  <h1>Create an Account for Mekase:</h1>

  <div class="col-md-4 col-md-offset-4">
    <%= render partial: "form" %>
  </div>

app/views/users/show.html.erb
  <h1><%= "#{@user.username.capitalize}" %>'s Meal Plans</h1>
  <%= button_to "Create New Meal Plan", new_user_day_path(@user), method: :get, class: "btn btn-default" %>
  <hr>
  <% @days.each do |day| %>
    <div class="col-sm-6 col-md-2">
      <div class="thumbnail">
        <div class="caption">
        <h4><%= link_to day.date.strftime('%A, %B %d, %Y'), user_day_path(@user, day) %></h4>
        <hr>
        <% day.recipes.each do |recipe| %>
          <h5><%= recipe.name %></h5>
          <h6>Calories per Serving: <%= recipe.calories_per_serving %><br></h6>
          <hr>
        <% end %>
         <strong>Total Calories:</strong> <%= day.total_calories %>
         <hr>
        <%= button_to "Edit Meal Plan", edit_user_day_form_path(@user, day), method: :get, class: "btn btn-default" %>
        <%= button_to "Delete Meal Plan", user_day_path(@user, day), method: :delete, class: "btn btn-default" %>
      </div>
    </div>
  </div>
  <% end %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Mekase!</h1>
    <h3>A meal planning and recipe sharing application for the masses.</h3>
</div>